builds:
  - binary: git-ssh-sign
    main: ./cmd/ssh-sign
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

  # Separated build for the MacOS binary for notarization
  - binary: git-ssh-sign
    id: "git-ssh-sign-macos"
    main: ./cmd/ssh-sign
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - format: binary

signs:
  - signature: "${artifact}"
    ids:
      - git-ssh-sign
    artifacts: binary
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
    output: true # for debugging

  - signature: "${artifact}"
    id: nondefault
    ids:
      - git-ssh-sign-macos
    cmd: gon
    args:
      - gon.hcl
    artifacts: all
    output: true
